"""
cli.py — Command-line interface for ku-wiki.

Commands:
  ku-wiki init     — Set up a new vault and .ku-wiki.toml config
  ku-wiki build    — Build wiki articles for a topic
  ku-wiki update   — Update existing topics, generate digest
  ku-wiki watch    — Run update on a schedule
  ku-wiki status   — Show vault stats and tracked topics
"""

from __future__ import annotations

import os
import sys
import time
import json
from pathlib import Path
from typing import Optional

import click
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn
from rich.table import Table
from rich.panel import Panel
from rich import print as rprint

from .ku_client import KUClient
from .compiler import WikiCompiler
from .vault_writer import VaultWriter
from .wikilink_graph import WikilinkGraph
from .digest import DigestGenerator


console = Console()

CONFIG_FILE = ".ku-wiki.toml"
DEFAULT_VAULT = "~/ObsidianVault"


def load_config(config_path: Optional[str] = None) -> dict:
    """Load .ku-wiki.toml from current dir or specified path."""
    paths = []
    if config_path:
        paths.append(Path(config_path))
    paths += [Path(".ku-wiki.toml"), Path.home() / ".ku-wiki.toml"]

    for p in paths:
        if p.exists():
            try:
                if sys.version_info >= (3, 11):
                    import tomllib
                    return tomllib.loads(p.read_text())
                else:
                    import tomli
                    return tomli.loads(p.read_text())
            except Exception:
                pass

    return {}


def get_client(config: dict, api_key: Optional[str] = None) -> KUClient:
    key = api_key or config.get("ku_api_key") or os.environ.get("KU_API_KEY", "")
    if not key:
        console.print("[red]❌ No KU API key found.[/red]")
        console.print("Set it via: [bold]export KU_API_KEY=ku_test_...[/bold]")
        console.print("Or add to .ku-wiki.toml: [bold]ku_api_key = \"ku_test_...\"[/bold]")
        sys.exit(1)
    return KUClient(api_key=key)


def get_vault(config: dict, vault_path: Optional[str] = None) -> str:
    return vault_path or config.get("vault_path") or os.environ.get("KU_WIKI_VAULT", DEFAULT_VAULT)


# ─── CLI group ────────────────────────────────────────────────────────────────

@click.group()
@click.version_option(version="0.1.0", prog_name="ku-wiki")
def main():
    """
    ku-wiki — Karpathy-style LLM wiki builder powered by Knowledge Universe API.

    \b
    Quick start:
      ku-wiki init --vault ~/MyVault
      ku-wiki build "transformer architecture" --vault ~/MyVault
      ku-wiki update --vault ~/MyVault
    """
    pass


# ─── init command ─────────────────────────────────────────────────────────────

@main.command()
@click.option("--vault", default=DEFAULT_VAULT, help="Path to Obsidian vault")
@click.option("--api-key", envvar="KU_API_KEY", help="Knowledge Universe API key")
def init(vault: str, api_key: str):
    """Initialize a new vault with ku-wiki structure and config."""

    vault_path = Path(vault).expanduser().resolve()

    console.print(Panel.fit(
        "[bold cyan]ku-wiki init[/bold cyan]\n"
        "Setting up your Knowledge Universe wiki vault.",
        border_style="cyan"
    ))

    # Create vault structure
    (vault_path / "wiki").mkdir(parents=True, exist_ok=True)
    (vault_path / "raw").mkdir(parents=True, exist_ok=True)

    # Write CLAUDE.md schema
    claude_md = _get_claude_md_template()
    (vault_path / "CLAUDE.md").write_text(claude_md)

    # Write example index
    index_md = _get_initial_index()
    (vault_path / "index.md").write_text(index_md)

    # Write config
    config_content = f'''# ku-wiki configuration
# Generated by ku-wiki init

ku_api_key = "{api_key or "YOUR_KU_API_KEY_HERE"}"
vault_path = "{vault_path}"
anthropic_api_key = "{os.environ.get("ANTHROPIC_API_KEY", "YOUR_ANTHROPIC_KEY_HERE")}"

# Default settings
default_difficulty = 3
default_formats = ["pdf", "github", "html", "video", "jupyter", "stackoverflow"]
max_results = 10

# Update schedule (for ku-wiki watch)
update_interval = "weekly"  # "daily" | "weekly"
'''
    config_path = Path(".ku-wiki.toml")
    config_path.write_text(config_content)

    console.print(f"[green]✅ Vault created:[/green] {vault_path}")
    console.print(f"[green]✅ Config written:[/green] {config_path.resolve()}")
    console.print()
    console.print("[bold]Next steps:[/bold]")
    console.print(f'  1. Edit [cyan].ku-wiki.toml[/cyan] — add your API keys')
    console.print(f'  2. [cyan]ku-wiki build "attention mechanism" --vault {vault_path}[/cyan]')
    console.print(f'  3. Open [cyan]{vault_path}[/cyan] in Obsidian')


# ─── build command ────────────────────────────────────────────────────────────

@main.command()
@click.argument("topic")
@click.option("--vault", envvar="KU_WIKI_VAULT", help="Path to Obsidian vault")
@click.option("--api-key", envvar="KU_API_KEY", help="Knowledge Universe API key")
@click.option("--anthropic-key", envvar="ANTHROPIC_API_KEY", help="Anthropic API key for LLM compilation")
@click.option("--difficulty", default=3, type=click.IntRange(1, 5), show_default=True, help="Source difficulty (1=beginner, 5=expert)")
@click.option("--formats", default=None, help="Comma-separated formats: pdf,github,html,video,jupyter,stackoverflow")
@click.option("--max-results", default=10, show_default=True, help="Max sources to retrieve")
@click.option("--overwrite", is_flag=True, default=False, help="Overwrite existing articles")
@click.option("--config", default=None, help="Path to .ku-wiki.toml")
def build(
    topic: str,
    vault: Optional[str],
    api_key: Optional[str],
    anthropic_key: Optional[str],
    difficulty: int,
    formats: Optional[str],
    max_results: int,
    overwrite: bool,
    config: Optional[str],
):
    """
    Build wiki articles for a TOPIC using Knowledge Universe API.

    \b
    Examples:
      ku-wiki build "attention mechanism"
      ku-wiki build "RAG retrieval" --difficulty 4 --formats pdf,github
      ku-wiki build "transformer architecture" --vault ~/MyVault --overwrite
    """
    cfg = load_config(config)
    vault_str = get_vault(cfg, vault)
    ku = get_client(cfg, api_key)
    anthropic_key = anthropic_key or cfg.get("anthropic_api_key") or os.environ.get("ANTHROPIC_API_KEY")

    vault_path = Path(vault_str).expanduser().resolve()
    writer = VaultWriter(vault_path)
    compiler = WikiCompiler(anthropic_api_key=anthropic_key)
    graph = WikilinkGraph(vault_path / "wiki")

    formats_list = formats.split(",") if formats else cfg.get(
        "default_formats",
        ["pdf", "github", "html", "video", "jupyter", "stackoverflow"]
    )

    # ── Step 1: Discover sources ──────────────────────────────────────────────
    console.print()
    console.print(Panel.fit(
        f"[bold cyan]Building wiki for:[/bold cyan] [white]{topic}[/white]\n"
        f"Vault: {vault_path}  |  Difficulty: {difficulty}  |  "
        f"LLM: {'Claude API' if compiler.has_llm else 'template mode'}",
        border_style="cyan"
    ))
    console.print()

    with console.status(f"[bold]Searching Knowledge Universe for '{topic}'...[/bold]"):
        try:
            discover = ku.discover(topic, difficulty=difficulty, formats=formats_list, max_results=max_results)
            coverage = ku.coverage(topic, difficulty=difficulty)
        except Exception as e:
            console.print(f"[red]❌ KU API error: {e}[/red]")
            sys.exit(1)

    console.print(f"[green]✓[/green] Found [bold]{discover.total_found}[/bold] sources "
                  f"([{'cache' if discover.cache_hit else 'cold'}] {discover.processing_time_ms:.0f}ms)")
    console.print(f"[green]✓[/green] Coverage: [bold]{coverage.overall_label}[/bold] "
                  f"({coverage.overall_score:.0%})")

    if coverage.gaps:
        console.print(f"[yellow]⚠[/yellow] Gaps: {', '.join(coverage.gaps[:2])}")

    console.print()

    if not discover.sources:
        console.print("[yellow]No sources found. Try a different topic or lower difficulty.[/yellow]")
        return

    # ── Step 2: Compile each source ───────────────────────────────────────────
    existing_titles = writer.get_existing_titles()
    compiled_count = 0
    skipped_count = 0

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
        console=console,
    ) as progress:
        task = progress.add_task("Compiling articles...", total=len(discover.sources))

        for source in discover.sources:
            progress.update(task, description=f"[cyan]{source.platform}[/cyan] {source.title[:45]}...")

            # Check coverage before compiling
            if writer.article_exists(source.title) and not overwrite:
                skipped_count += 1
                progress.advance(task)
                continue

            # Compile
            try:
                markdown = compiler.compile(source, existing_titles)
                path = writer.write_article(source, markdown, overwrite=overwrite)
                existing_titles.append(source.title)
                compiled_count += 1
                progress.advance(task)
            except Exception as e:
                console.print(f"\n[yellow]⚠ Skipped {source.title[:40]}: {e}[/yellow]")
                progress.advance(task)

    # ── Step 3: Rebuild wikilinks ─────────────────────────────────────────────
    with console.status("[bold]Rebuilding wikilink graph...[/bold]"):
        link_stats = graph.rebuild_links()

    # ── Step 4: Update index ──────────────────────────────────────────────────
    with console.status("[bold]Updating index.md...[/bold]"):
        writer.update_index()
        writer.record_topic(topic, discover.total_found, coverage.overall_score)

    # ── Summary ───────────────────────────────────────────────────────────────
    console.print()

    table = Table(show_header=False, box=None, padding=(0, 2))
    table.add_column(style="green")
    table.add_column()
    table.add_row("✅ Articles compiled", str(compiled_count))
    table.add_row("⏭  Articles skipped", str(skipped_count))
    table.add_row("🔗 Wikilinks injected", str(link_stats["injected"]))
    table.add_row("📁 Vault location", str(vault_path))
    console.print(table)

    console.print()
    console.print(f"[bold green]Done![/bold green] Open [cyan]{vault_path}[/cyan] in Obsidian → "
                  f"Graph View to see the knowledge graph.")
    console.print()
    console.print(f"[dim]Next: [/dim][cyan]ku-wiki update --vault {vault_path}[/cyan] "
                  f"[dim](run weekly to stay current)[/dim]")


# ─── update command ───────────────────────────────────────────────────────────

@main.command()
@click.option("--vault", envvar="KU_WIKI_VAULT", help="Path to Obsidian vault")
@click.option("--api-key", envvar="KU_API_KEY", help="Knowledge Universe API key")
@click.option("--anthropic-key", envvar="ANTHROPIC_API_KEY", help="Anthropic API key")
@click.option("--since-days", default=7, show_default=True, help="Look back N days for new sources")
@click.option("--config", default=None, help="Path to .ku-wiki.toml")
@click.option("--webhook", default=None, help="Slack/Discord webhook URL for notifications")
def update(
    vault: Optional[str],
    api_key: Optional[str],
    anthropic_key: Optional[str],
    since_days: int,
    config: Optional[str],
    webhook: Optional[str],
):
    """
    Update existing wiki topics — find what's new, recompile changed articles.

    Generates a 'What Changed This Week' digest note in the vault.

    \b
    Examples:
      ku-wiki update
      ku-wiki update --since-days 14
      ku-wiki update --webhook https://hooks.slack.com/...
    """
    cfg = load_config(config)
    vault_str = get_vault(cfg, vault)
    ku = get_client(cfg, api_key)
    anthropic_key = anthropic_key or cfg.get("anthropic_api_key") or os.environ.get("ANTHROPIC_API_KEY")
    webhook_url = webhook or cfg.get("webhook_url")

    vault_path = Path(vault_str).expanduser().resolve()
    writer = VaultWriter(vault_path)
    compiler = WikiCompiler(anthropic_api_key=anthropic_key)
    graph = WikilinkGraph(vault_path / "wiki")
    digest_gen = DigestGenerator()

    tracked_topics = writer.get_tracked_topics()

    if not tracked_topics:
        console.print("[yellow]No topics tracked yet.[/yellow]")
        console.print("Build some topics first: [cyan]ku-wiki build \"your topic\"[/cyan]")
        return

    console.print()
    console.print(Panel.fit(
        f"[bold cyan]ku-wiki update[/bold cyan]\n"
        f"Checking {len(tracked_topics)} tracked topics for new sources (last {since_days} days)",
        border_style="cyan"
    ))
    console.print()

    diffs = {}
    coverages = {}
    articles_updated = []
    existing_titles = writer.get_existing_titles()

    for topic in tracked_topics:
        with console.status(f"Checking '{topic}'..."):
            try:
                diff = ku.diff(topic, since_days=since_days)
                coverage = ku.coverage(topic)
                diffs[topic] = diff
                coverages[topic] = coverage
            except Exception as e:
                console.print(f"[yellow]⚠ Could not check '{topic}': {e}[/yellow]")
                continue

        velocity_emoji = {"fast-moving": "🚀", "active": "📈", "stable": "📊", "mature": "📚"}.get(
            diff.field_velocity, "❓"
        )
        console.print(
            f"  {velocity_emoji} [bold]{topic}[/bold]: "
            f"{diff.new_count} new sources | {diff.field_velocity}"
        )

        # Compile new sources
        for source in diff.new_sources[:3]:
            try:
                markdown = compiler.compile(source, existing_titles)
                writer.write_article(source, markdown, overwrite=True)
                articles_updated.append(source.title)
                existing_titles.append(source.title)
            except Exception as e:
                console.print(f"[dim]  ⚠ Could not compile {source.title[:40]}: {e}[/dim]")

    # Rebuild graph and index
    with console.status("[bold]Rebuilding graph...[/bold]"):
        graph.rebuild_links()
        writer.update_index()

    # Generate digest
    digest_md = digest_gen.generate(diffs, coverages, articles_updated, since_days)
    digest_path = writer.write_digest("weekly-update", digest_md)

    # Send webhook if configured
    if webhook_url:
        _send_webhook(webhook_url, diffs, articles_updated)

    console.print()
    console.print(f"[green]✅ Update complete.[/green]")
    console.print(f"[green]✅ Digest note:[/green] {digest_path.relative_to(vault_path)}")
    console.print(f"[green]✅ Articles updated:[/green] {len(articles_updated)}")


# ─── watch command ────────────────────────────────────────────────────────────

@main.command()
@click.option("--vault", envvar="KU_WIKI_VAULT", help="Path to Obsidian vault")
@click.option("--api-key", envvar="KU_API_KEY", help="Knowledge Universe API key")
@click.option("--interval", default="weekly", type=click.Choice(["daily", "weekly"]), show_default=True)
@click.option("--config", default=None, help="Path to .ku-wiki.toml")
@click.option("--webhook", default=None, help="Slack/Discord webhook URL")
def watch(
    vault: Optional[str],
    api_key: Optional[str],
    interval: str,
    config: Optional[str],
    webhook: Optional[str],
):
    """
    Run update on a schedule — keeps your wiki current automatically.

    \b
    Examples:
      ku-wiki watch --interval weekly
      ku-wiki watch --interval daily --webhook https://hooks.slack.com/...
    """
    try:
        import schedule
    except ImportError:
        console.print("[red]❌ schedule package required: pip install schedule[/red]")
        sys.exit(1)

    cfg = load_config(config)
    vault_str = get_vault(cfg, vault)

    seconds = 7 * 24 * 3600 if interval == "weekly" else 24 * 3600
    interval_label = "weekly" if interval == "weekly" else "daily"

    console.print(Panel.fit(
        f"[bold cyan]ku-wiki watch[/bold cyan]\n"
        f"Running [bold]{interval_label}[/bold] updates on vault: {vault_str}\n"
        f"Press Ctrl+C to stop.",
        border_style="cyan"
    ))

    def run_update():
        console.print(f"\n[bold cyan]Running scheduled update...[/bold cyan]")
        from click.testing import CliRunner
        runner = CliRunner()
        result = runner.invoke(update, [
            "--vault", vault_str,
            "--api-key", api_key or cfg.get("ku_api_key", ""),
            *(["--webhook", webhook] if webhook else []),
        ])
        if result.output:
            console.print(result.output)

    # Run immediately on start
    run_update()

    if interval == "weekly":
        schedule.every().week.do(run_update)
    else:
        schedule.every().day.do(run_update)

    console.print(f"\n[dim]Next update in {interval_label}. Watching...[/dim]")

    try:
        while True:
            schedule.run_pending()
            time.sleep(60)
    except KeyboardInterrupt:
        console.print("\n[yellow]Watch stopped.[/yellow]")


# ─── status command ───────────────────────────────────────────────────────────

@main.command()
@click.option("--vault", envvar="KU_WIKI_VAULT", help="Path to Obsidian vault")
@click.option("--config", default=None, help="Path to .ku-wiki.toml")
def status(vault: Optional[str], config: Optional[str]):
    """Show vault status: article count, tracked topics, graph stats."""
    cfg = load_config(config)
    vault_str = get_vault(cfg, vault)
    vault_path = Path(vault_str).expanduser().resolve()

    if not vault_path.exists():
        console.print(f"[red]❌ Vault not found: {vault_path}[/red]")
        console.print("Run: [cyan]ku-wiki init --vault <path>[/cyan]")
        return

    writer = VaultWriter(vault_path)
    graph = WikilinkGraph(vault_path / "wiki")
    state = writer.load_state()
    graph_stats = graph.get_stats()

    console.print()
    console.print(Panel.fit(
        f"[bold cyan]Knowledge Universe Wiki — Status[/bold cyan]\n"
        f"Vault: {vault_path}",
        border_style="cyan"
    ))
    console.print()

    # Overview table
    table = Table(show_header=True, header_style="bold cyan", box=None, padding=(0, 2))
    table.add_column("Metric")
    table.add_column("Value", justify="right")

    table.add_row("Total articles", str(graph_stats["total_articles"]))
    table.add_row("Total wikilinks", str(graph_stats["total_links"]))
    table.add_row("Avg links/article", str(graph_stats["avg_links_per_article"]))
    table.add_row("Orphan articles", str(graph_stats["orphan_articles"]))
    table.add_row("Last updated", state.get("last_update", "Never")[:10] if state.get("last_update") else "Never")

    console.print(table)
    console.print()

    # Tracked topics
    topics = state.get("topics", {})
    if topics:
        console.print("[bold]Tracked topics:[/bold]")
        t_table = Table(show_header=True, header_style="bold", box=None, padding=(0, 2))
        t_table.add_column("Topic")
        t_table.add_column("Last built", justify="right")
        t_table.add_column("Sources", justify="right")
        t_table.add_column("Coverage", justify="right")

        for topic, info in sorted(topics.items()):
            t_table.add_row(
                topic,
                info.get("last_built", "?"),
                str(info.get("source_count", "?")),
                f"{float(info.get('coverage_score', 0)):.0%}",
            )
        console.print(t_table)
        console.print()

    # Most linked
    if graph_stats["most_linked"]:
        console.print("[bold]Most-linked articles:[/bold]")
        for title, count in graph_stats["most_linked"]:
            console.print(f"  [[{title}]] — {count} backlinks")
        console.print()


# ─── Helper functions ─────────────────────────────────────────────────────────

def _send_webhook(webhook_url: str, diffs: dict, articles_updated: list[str]):
    """Send a Slack/Discord webhook notification."""
    try:
        import httpx
        total_new = sum(d.new_count for d in diffs.values())
        text = (
            f"📚 *ku-wiki update complete*\n"
            f"• {total_new} new sources discovered\n"
            f"• {len(articles_updated)} articles updated\n"
            f"• Topics: {', '.join(list(diffs.keys())[:5])}"
        )
        payload = {"text": text}  # Slack format
        # Discord uses "content" key
        httpx.post(webhook_url, json=payload, timeout=10)
        httpx.post(webhook_url, json={"content": text}, timeout=10)
    except Exception:
        pass  # Webhook failure is non-fatal


def _get_claude_md_template() -> str:
    return '''# Wiki Schema — Knowledge Universe Wiki Builder

## Role

You are the knowledge compiler for this personal wiki.
Process raw sources. Write synthesized wiki articles.
The LLM is the compiler. Obsidian is the IDE. This wiki is the codebase.

## Formatting rules

- YAML frontmatter is provided externally — do not modify it
- Headings: sentence case. ## for main sections, ### for subsections
- Wikilinks: [[concept name]] for any concept with its own article
- Maximum article length: 500 words
- No fluff. No filler. Be specific.

## Sections (use as relevant)

### ## What this is
One paragraph. Dense. Precise.

### ## How it works / Key ideas
The mechanism. Not just what it is — how it operates.

### ## Why it matters
Practical significance. Real use cases.

### ## Related concepts
[[wikilinks]] to connected articles.

### ## Primary sources
- [Title](url) — *freshness label*

## What this wiki is

Built with [ku-wiki](https://github.com/VLSiddarth/ku-obsidian-wiki).
Powered by the [Knowledge Universe API](https://vlsiddarth-knowledge-universe.hf.space).

Every article knows its own decay score. Stale knowledge is visible.
'''


def _get_initial_index() -> str:
    from datetime import date
    today = date.today().isoformat()
    return f'''---
title: Knowledge Universe Wiki
last_updated: {today}
---

# Knowledge Universe Wiki

> Built with [ku-wiki](https://github.com/VLSiddarth/ku-obsidian-wiki)
> Powered by [Knowledge Universe API](https://vlsiddarth-knowledge-universe.hf.space)

## Getting started

1. Run `ku-wiki build "your topic"` to add articles
2. Open this vault in Obsidian
3. Use Graph View to explore the knowledge graph
4. Run `ku-wiki update` weekly to stay current

## Articles

*(Articles will appear here after your first build)*
'''
