"""
digest.py — Generates "What Changed This Week" digest notes.

Runs after ku-wiki update. Produces a Markdown summary of:
  - New sources discovered per topic
  - Field velocity (fast-moving vs stable)
  - Articles refreshed
  - Coverage gaps detected

The digest note drops into vault/wiki/_what-changed-<date>.md
"""

from __future__ import annotations

from datetime import date
from typing import Optional

from .ku_client import DiffResult, CoverageResult, KUSource


VELOCITY_EMOJI = {
    "fast-moving": "🚀",
    "active":      "📈",
    "stable":      "📊",
    "mature":      "📚",
    "unknown":     "❓",
}

FRESHNESS_EMOJI = {
    "fresh":   "🟢",
    "aging":   "🟡",
    "stale":   "🔴",
    "unknown": "⚪",
}


class DigestGenerator:
    """
    Generates weekly digest notes summarizing what changed in the wiki.
    """

    def generate(
        self,
        diffs: dict[str, DiffResult],
        coverages: dict[str, CoverageResult],
        articles_updated: list[str],
        since_days: int = 7,
    ) -> str:
        """
        Generate the full digest Markdown.

        Args:
            diffs: {topic: DiffResult} for each tracked topic
            coverages: {topic: CoverageResult} for each tracked topic
            articles_updated: list of article titles that were recompiled
            since_days: the time window for the diff
        """
        today = date.today().isoformat()

        total_new = sum(d.new_count for d in diffs.values())
        fast_moving = [t for t, d in diffs.items() if d.field_velocity in ("fast-moving", "active")]
        slow_moving = [t for t, d in diffs.items() if d.field_velocity in ("stable", "mature")]

        lines = [
            "---",
            f'title: "What changed — {today}"',
            f"tags:",
            "  - digest",
            "  - changelog",
            f"ku_compiled: {today}",
            "---",
            "",
            f"# What changed this week — {today}",
            "",
            f"> Digest covering the past {since_days} days. "
            f"Generated by [ku-wiki](https://github.com/VLSiddarth/ku-obsidian-wiki).",
            "",
        ]

        # Summary block
        lines += [
            "## Summary",
            "",
            f"- **{total_new}** new sources discovered across {len(diffs)} tracked topics",
            f"- **{len(articles_updated)}** wiki articles updated",
            f"- **{len(fast_moving)}** topics moving fast: {', '.join(fast_moving) if fast_moving else 'none'}",
            f"- **{len(slow_moving)}** topics stable: {', '.join(slow_moving) if slow_moving else 'none'}",
            "",
        ]

        # Per-topic breakdown
        if diffs:
            lines += ["## What changed by topic", ""]

            for topic, diff in sorted(diffs.items()):
                velocity = diff.field_velocity
                emoji = VELOCITY_EMOJI.get(velocity, "❓")
                coverage = coverages.get(topic)
                coverage_str = ""
                if coverage:
                    coverage_str = f" · coverage: {coverage.overall_score:.0%}"

                lines += [
                    f"### {emoji} {topic}",
                    "",
                    f"Field velocity: **{velocity}**{coverage_str}  ",
                    f"New sources: **{diff.new_count}** · Established: **{diff.established_count}**",
                    "",
                ]

                if diff.new_sources:
                    lines.append("**New this week:**")
                    lines.append("")
                    for src in diff.new_sources[:5]:
                        freshness = src.decay.label if src.decay else "unknown"
                        icon = FRESHNESS_EMOJI.get(freshness, "⚪")
                        age = f"{src.decay.age_days}d" if src.decay and src.decay.age_days >= 0 else "?"
                        lines.append(
                            f"- {icon} [{src.title}]({src.url}) "
                            f"— *{src.platform}* · age: {age} · q: {src.quality_score:.1f}"
                        )
                    lines.append("")

                if coverage and coverage.gaps:
                    lines.append("**Coverage gaps:**")
                    lines.append("")
                    for gap in coverage.gaps[:3]:
                        lines.append(f"- ⚠️ {gap}")
                    lines.append("")

        # Updated articles
        if articles_updated:
            lines += [
                "## Articles updated this week",
                "",
            ]
            for title in sorted(articles_updated):
                lines.append(f"- [[{title}]]")
            lines.append("")

        # Action items
        lines += [
            "## Suggested next topics",
            "",
            "> Based on coverage gaps and wikilink stubs in existing articles.",
            "",
        ]

        # Find topics with low coverage as suggestions
        suggestions = [
            t for t, c in coverages.items()
            if c.overall_score < 0.5
        ]
        if suggestions:
            for s in suggestions[:5]:
                lines.append(f"- `ku-wiki build \"{s}\"`")
        else:
            lines.append("- *(no gaps detected — wiki coverage is strong)*")

        lines += [
            "",
            "---",
            "",
            f"*Digest generated automatically by ku-wiki on {today}*",
        ]

        return "\n".join(lines)

    def generate_minimal(self, topic: str, diff: DiffResult) -> str:
        """Generate a minimal per-topic update note for new sources only."""
        today = date.today().isoformat()
        velocity = diff.field_velocity
        emoji = VELOCITY_EMOJI.get(velocity, "❓")

        lines = [
            f"# {emoji} {topic} — {today}",
            "",
            f"*{diff.new_count} new sources in the last {diff.since_days} days. "
            f"Field velocity: {velocity}.*",
            "",
        ]

        for src in diff.new_sources[:8]:
            freshness = src.decay.label if src.decay else "unknown"
            icon = FRESHNESS_EMOJI.get(freshness, "⚪")
            lines.append(
                f"- {icon} [{src.title}]({src.url}) — *{src.platform}*"
            )

        return "\n".join(lines)
